name: PyOxidizer Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  linux_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install PyOxidizer
      run: cargo install pyoxidizer
    - name: Build visidata-oxide
      run: pyoxidizer build
    - uses: actions/upload-artifact@v2
      with:
        name: linux_build
        path: build/*/debug/install/

  windows_build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install PyOxidizer
      run: cargo install pyoxidizer
    - name: Build visidata-oxide
      run: pyoxidizer build
    - uses: actions/upload-artifact@v2
      with:
        name: windows_build
        path: build/*/debug/install/

  macos_build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install PyOxidizer
      run: cargo install pyoxidizer
    - name: Build visidata-oxide
      run: pyoxidizer build
    - uses: actions/upload-artifact@v2
      with:
        name: macos_build
        path: build/*/debug/install/
