name: PyOxidizer Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build-triple: x86_64-unknown-linux-gnu
          - os: windows-latest
            build-triple: x86_64-pc-windows-msvc
          - os: macos-latest
            build-triple: x86_64-apple-darwin

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install PyOxidizer
      run: cargo install pyoxidizer
    - name: Build visidata-oxide
      run: pyoxidizer build
    - uses: actions/upload-artifact@v2
      with:
        name: visidata-oxide-${{ github.ref }}-${{ matrix.os }}
        path: build/${{ matrix.build-triple }}/debug/install/
