name: PyOxidizer Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install PyOxidizer
      run: cargo install pyoxidizer
    - name: Build visidata-oxide
      run: pyoxidizer build
    - uses: actions/upload-artifact@v2
      with:
        name: ubuntu-build
        path: build/*/debug/install/
